### ISSUE TITLE
Add support for real-time-only streams, no storage/recording

### ISSUE THREAD

**Issue by bsaxen** [ioants/ioant#11]
Proposal: top topic can be, i.e. rt/global/local/...  (rt = real-time only). 
live/global/local/... will be both real-time and storage/recording

This is applicable to robot applications when generating a lot of temporary data from sensors.

**Comment by asaxen** [comment]
This feature has nothing todo with collector. I will remove that tag.

**Comment by bsaxen** [comment]
Avoid use "live" top topic. Close issue!
